### ISSUE TITLE
Chiarire obbligatorietà di applicazione dei profili di sicurezza.

### ISSUE THREAD

**Issue by ioggstream** [italia/lg-modellointeroperabilita-docs#103]
## Obbligatorietà di applicazione dei profili di sicurezza

Il documento riporta qui 

- https://github.com/italia/lg-modellointeroperabilita-docs/blame/master/doc/doc_04_cap_00.rst#L5

> Il presente documento descrive i *profili* di sicurezza individuati da AgID che i
> soggetti erogatori DOVREBBERO utilizzare per soddisfare le necessità

## Da chiarire

Mi facevano notare che questa opzionalità si applica anche a misure che reputiamo obbligatorie:

  - algoritmi, elementi di wsse e jwt

## Una possibile soluzione
In due passaggi:

  - chiarire che il vincolo sugli algoritmi è indipendente dai profili;
  - chiarire che in qualsiasi soluzione di autenticazione/autorizzazione/integrità implementate il livello di tutela deve essere equivalente a quello delle soluzioni prospettate.

**Comment by leptoquark** [comment]
risolta
