### ISSUE TITLE
Verificare l'utilizzo di 303 See Other in NONBLOCK_PULL_REST

### ISSUE THREAD

**Issue by ioggstream** [italia/lg-modellointeroperabilita-docs#145]
## Mi aspetto

che le indicazioni in NONBLOCK_PULL_REST siano conformi a https://httpwg.org/http-core/draft-ietf-httpbis-semantics-latest.html#status.303

## Invece

- 303 in risposta a GET si usa quando il server non ha una rappresentazione per la risorsa, e rimanda altrove (eg. anche a un altro server);
- nell'esempio manca l'header `Location`; 
- nell'esempio il payload contiene un json quando dovrebbe contenere un hypertext che referenzia il contenuto di Location
> the representation of a 303 response ought to contain a short hypertext note
> with a hyperlink to the same URI reference provided in the Location header field.

## Note

Chiarirei che

- le relazioni tra gli URL (eg. /M -> /M/{uuid} -> /M/{uuid}/result ) non sono normative, e che a seconda del servizio non è necessario che siano tutti sotto la stessa alberatura; in particolare terminato il processamento la risorsa /M/{uuid} nella forma attuale non è più necessaria poiché il server redireziona altrove il client con un 303
- nella forma attuale non è chiaro se ulteriori richieste a `/M/{uuid}` redirigano ulteriormente a `/M/{uuid}/result` (in tal caso 301 Moved Permanently potrebbe essere appropriato) 

## Proposta

1- non usare 303 (anche se fosse un 200, l'header Location potrebbe comunque indicare l'indirizzo della risorsa finale)
2- alleggerire il profilo in modo che quello attuale sia una possibilità di implementazione, ma non l'unica possibile

cc: @vintra73

**Comment by vintra73** [comment]
Di seguito le mie al volo.

MI ASPETTO:
l'attuale formulazione del requirement che impatta sul 303 è "Al passo (4) l’erogatore indica, sulla base dello stato del processamento, che la risorsa non è ancora pronta (il codice HTTP restituito è HTTP status 200 OK) o indica che la risorsa è pronta, utilizzando HTTP header Location, per indicare il percorso dove recuperare la risorsa (il codice HTTP restituito è HTTP status 303 See Other"... cosa ritiene che sia utile per allinearlo al riferimento che dati (segnalo che è un draft). L'allineamento dell'esempio lo lascio a te.

NOTE: 
ti riferisci sempre al pattern NONBLOCK_PULL_REST oppure in generale? non riesco a contestualizzare

PROPOSTA
1. ma non capisco le tue deduzioni sull'utilizzo del 303, nello specifico quando dici di "non usare", perché?
2. cosa vuoi dire con altra implementazione? nel MODI si individuano i pattern per definire un modo di utilizzo delle tecnologie per risolvere un problema specifico in maniera condivisa, se cominciamo ad aggiungere nei pattern il concetto si fa cosi ma anche in un altro modo mi chiedo se non stiamo rompendo quanto delineato, le altre possibilità non sono impedite dal MODI vanno declinate

**Comment by ioggstream** [comment]
Se non è una buona prassi indicare un payload nel 303 (a meno che non abbia il solo link) non lo userei, cmq ho chiesto info sul 303 qui https://github.com/httpwg/http-extensions/pull/690 vediamo che dicono. cc @mfortini

**Comment by ioggstream** [comment]
Fixed #247
