### ISSUE TITLE
Indicare di non usare `Content-MD5` ma `Digest` invece.

### ISSUE THREAD

**Issue by ioggstream** [italia/lg-modellointeroperabilita-docs#26]
Alla luce della discussione in https://trac.ietf.org/trac/httpbis/ticket/178 ripresa in https://github.com/martinthomson/http-mice/issues/11
andrebbe verificato l'utilizzo di `Content-MD5`.

1- Usando la teminologia usata in RFC7230, il  `Content-MD5` definito in [RFC2616](https://tools.ietf.org/html/rfc2616#section-14.15) è una proprietà del `message` iniziale e non della [representation](https://httpwg.org/specs/rfc7231.html#representations). Questo significa che:

  - in una range-request, il `Content-MD5` viene calcolato sul [payload body](https://httpwg.org/specs/rfc7230.html#message.body) (parziale) dell'oggetto e non sulla sua intera [selected representation](https://httpwg.org/specs/rfc7231.html#representations)
  - come `Digest` include il content-coding ma non il transfer-coding che può essere applicato successivamente da intermediari
  - non essendo associato alla `representation` (eg a differenza dell'ETAG) è un identificatore ambiguo per gli scambi firmati e/o il non ripudio

2- Le nuove specifiche HTTP rimuovono i riferimenti a `Content-MD5` (che è possibile considerare deprecato) per i motivi di cui sopra. AWS lo utilizza dal 2006 e continua ad utilizzarlo (non ha il problema dell'interoperabilità e la semantica per upload e download dei file è ben definita).

**Comment by giacomo83** [comment]
Non trovo riferimenti a Content-MD5 nel doc, forse l'issue è obsoleta?

**Comment by ioggstream** [comment]
@giacomo83 l'unica cosa da dire è di *evitare* `Content-MD5` per i motivi indicati qui sopra e di utilizzare `Digest`.

**Comment by ioggstream** [comment]
WIP in #96

**Comment by ioggstream** [comment]
Merged #96
